services:
  frankenphp:
    build: .
    image: custom-frankenphp:8.4
    container_name: frankenphp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/app/public
      #- ./caddy/site.caddyfile:/etc/caddy/Caddyfile.d/site.caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: ${DOMAIN:-localhost}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-franken}
      MYSQL_USER: ${MYSQL_USER:-frankenuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-frankenpass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  caddy_data:
  caddy_config: